### ISSUE TITLE
Document how to build the project

### ISSUE THREAD

**Issue by Nilzor** [pbreault/adb-idea#34]
The README.md documents how to use the plugin but not how to build it. I'd like to fork and possibly contribute to the project but I'm new to plugin development, so a quick 1-2-3 cookbook style introduction on how to build the project would be nice.

**Comment by hibob224** [comment]
Would be appreciated as well, have managed to get the plugin to build but when attempting to use any command the plugin can't find any devices.

**Comment by julioz** [comment]
I would also love to contribute to this project, but a quick cookbook as @Nilzor mentioned would be great as a "getting started". @pbreault Can you help us here? I'm pretty sure this will make more PRs to come in the future of this amazing plugin.

**Comment by eliasbagley** [comment]
+1

**Comment by fmatosqg** [comment]
+1.

I've managed to get an almost successfull build with gradle, but since then I changed computers and need to start from scratch again.

@pbreault would you be interested in merging a gradle build in case mine works? It drops the configuration to a minimum, and I'd be providing the documentation for it.

**Comment by pbreault** [comment]
@fmatosqg I would love it, creating a working gradle build is on my radar but I haven't got around to doing it yet. I tried to use https://github.com/JetBrains/gradle-intellij-plugin a while back but couldn't get it to work because it only fetches the core intellij distribution without any plugin... which means that adb idea can't compile since it has a strong dependency on the android plugin jar.

I can try to help you troubleshoot your issue if you submit a PR.

Meanwhile I'll flesh out the documentation on how to setup the project (which is not exactly easy because of the aforementioned dependency on the android plugin)
Thanks

**Comment by fmatosqg** [comment]
I created https://github.com/pbreault/adb-idea/pull/43 with an included android.jar copied from AS preview. What I did was download the latest preview from the canary channel and copy that single jar over this project, to be able to compile against the newest version of this dependency.

As I noticed you're making updates to make the plugin compatible with the bleeding edge of Android Studio canary, that's obviously not on the map for the gradle-intellij-plugin so far, so there's no easy way around it. I commented on it with Zolotov who's been very helpful and appears to be a driving force behind that plugin (https://intellij-support.jetbrains.com/hc/en-us/community/posts/206749645-Building-plugins-that-depends-on-android-using-gradle-plugin?page=1#community_comment_207150085). 

If you wanted to build an intellij compatible version you can simply tap into the android plugin for the latest intellij version by including "plugin: android" in the gradle file, which I probably should have turned off on that PR. I'm still to understand if there's a repository anywhere to download Android Studio versions of that android.jar file, which will certainly solve the problem for adb-plugin as far as I've tested..

**Comment by fmatosqg** [comment]
Should be covered by https://github.com/pbreault/adb-idea/blob/master/DEVELOP.md, can we close this issue?

**Comment by androidBsat** [comment]
how to build your project ?  I have try very times and failed.  help me,  I use Intellij .

**Comment by vectorzeng** [comment]
> Should be covered by https://github.com/pbreault/adb-idea/blob/master/DEVELOP.md, can we close this issue?

Misspelling  task name .

look at this：
https://github.com/vectorzeng/adb-idea/blob/master/DEVELOP.md

**Comment by fmatosqg** [comment]
I'd vote to close it :)
Let me know if something is missing and I'd add it.

**Comment by vectorzeng** [comment]
> Should be covered by https://github.com/pbreault/adb-idea/blob/master/DEVELOP.md, can we close this issue?

@fmatosqg 
can you merge the pull request?
https://github.com/pbreault/adb-idea/pull/116

**Comment by Nilzor** [comment]
DEVELOP.md should cover it yes (haven't tested though). Nice to be able to close a 4+ year old issue :-)
